apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: my-application-nodejs-sample
  namespace: marialeonova
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: my-application
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: my-application-nodejs-sample
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: my-application-nodejs-sample-
      labels:
        build.appstudio.openshift.io/application: my-application
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: my-application-nodejs-sample
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: marialeonova
    spec:
      params:
      - name: git-url
        value: https://github.com/nodeshift-starters/devfile-sample.git
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:marialeonova-my-application-nodejs-sample-$(tt.params.git-revision)
      - name: dockerfile
        value: Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:13f5d9c921b3f727684a00084037f673a0dc4273
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: my-application-nodejs-sample/$(tt.params.git-revision)
    status: {}
status: {}
